### ISSUE TITLE
Disable Backup Gesture of 2.5 won't work

### ISSUE THREAD

**Issue by CySxL** [Paisseon/Reverie#1]
As title said. Even I disabled the backup gesture toggle but I can still leave hibernation from pressing lock button once.

And also in preference panel Reverie showing 2.5 but it shows 2.6 in repo/Cydia meanwhile.

**Comment by CySxL** [comment]
![image](https://user-images.githubusercontent.com/15531137/148727855-65d01bdd-5e74-42f3-9ffe-a54190cb0775.jpeg)

**Comment by CySxL** [comment]
Also I don't know if it's intended but leaving hibernation won't perform a sbreload/resping in 2.5/2.6 right now.

**Comment by Paisseon** [comment]
Not respringing is intentional, I found a much faster method of waking. Will fix the other issues though!

**Comment by CySxL** [comment]
Thanks a lot !! <3

**Comment by CySxL** [comment]
> Not respringing is intentional, I found a much faster method of waking. Will fix the other issues though!

I just thought of if hibernation will kill/terminate the running Apps ? Cuz if it does not then would it consume more battery than killing Apps ?

**Comment by Paisseon** [comment]
I've tried to add this before but it would always safe-mode me upon hibernating, which of course would immediately end hibernation. I still intend to add it at *some point* but Reverie isn't currently on the top of my priorities

**Comment by Paisseon** [comment]
Also just realised that I forgot to upload the fixed version to my repo, it's been sitting around in my packages folder for days 🤦‍♀️

**Comment by CySxL** [comment]
Saw the update and it works nice :D thanks a lot hahaha. Oh and no rush for the implement🥰
