### ISSUE TITLE
[Bug] FaceID auto-unlock doesn't work

### ISSUE THREAD

**Issue by CySxL** [Paisseon/Reverie#2]
After using Reverie(2.7.2) once, the auto-scan and unlock of FaceID stops working. 

Only works when user manually swipes up on lockscreen to unlock.

Respring once can easily fix it, but this issue doesn't happen on 2.6.2 build.

**Comment by Paisseon** [comment]
Pushed an update that fixes this, 2.7.3 :)

**Comment by CySxL** [comment]
> Pushed an update that fixes this, 2.7.3 :)

Thanks a lot !!

May I ask if the CPU throttling option still exists in 2.7.3 build ? Since I can't find the option beyond the builds compiled with Orion.

**Comment by Paisseon** [comment]
Nah, I removed that when I found the Mario version of Powercuff. It works a lot better than my attempt did, and can be set to activate when the screen is off (so it works with Reverie)

**Comment by CySxL** [comment]
Oh nyo... I don't use Powercuff at all. Can u add it back for Reveire tho ?
